import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerListTool } from './list.js';
import { registerInfoTool } from './info.js';
import { registerDoctorTool } from './doctor.js';
import { registerOntologyStatusTool } from './ontology-status.js';
import { registerOntologyGenerateTool } from './ontology-generate.js';
import { registerOntologyRefreshTool } from './ontology-refresh.js';
import { registerInitTool } from './init.js';
import { registerUpdateTool } from './update.js';
import { registerMigrateTool } from './migrate.js';
import { registerOntologyDomainWriteTool } from './ontology-domain-write.js';
import { registerMemoryAddTool } from './memory-add.js';
import { registerMemoryListTool } from './memory-list.js';
import { registerDashboardTool } from './dashboard.js';
import { registerSetupTool } from './setup.js';
import { registerWorkflowTool } from './workflow.js';
import { registerSyncTool } from './sync.js';
import { registerQualityCheckTool } from './quality-check.js';
import { registerOntologyAnnotationsTool } from './ontology-annotations.js';

export function registerAllTools(server: McpServer): void {
  registerListTool(server);
  registerInfoTool(server);
  registerDoctorTool(server);
  registerOntologyStatusTool(server);
  registerOntologyGenerateTool(server);
  registerOntologyRefreshTool(server);
  registerOntologyDomainWriteTool(server);
  registerInitTool(server);
  registerUpdateTool(server);
  registerMigrateTool(server);
  registerMemoryAddTool(server);
  registerMemoryListTool(server);
  registerDashboardTool(server);
  registerSetupTool(server);
  registerWorkflowTool(server);
  registerSyncTool(server);
  registerQualityCheckTool(server);
  registerOntologyAnnotationsTool(server);
}
